name: Android CI

# Trigger the workflow on push
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run spotless check
        run: ./gradlew spotlessCheck

      - name: Run spotless code fix
        run: ./gradlew spotlessApply

      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: spotless_report.html
          path: app/build/reports/spotless-results-debug.html

      - name: Check Kotlin Formatting
        run: ./gradlew ktlintCheck --continue

      - name: Upload html ktlint report
        uses: actions/upload-artifact@v2
        with:
          name: ktlint.html
          path: app/build/reports/ktlint-result-debug.html

  build-documentation:
    needs: [ lint ]
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run spotless check
        run: ./gradlew dokkaHtml

      - name: Upload html documentation
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/documentation/html/index.html

  unit-test:
    needs: [ lint ]
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run tests
        run: ./gradlew test

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

  build:
    needs: [ unit-test ]
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload app
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk/debug/**.apk