name: Android CI

# Trigger the workflow on push
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run spotless check
        run: ./gradlew spotlessCheck

      - name: Run spotless code fix
        run: ./gradlew spotlessApply

  build-documentation:
    needs: [ lint ]
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

#      - name: Set up JDK
#        uses: actions/setup-java@v2
#        with:
#          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate documentation
        if: ${{github.event_name == 'push'}}
        run: ./gradlew dokkaHtml

      - name: Deploy API documentation to Github Pages
        if: ${{github.event_name == 'push'}}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: app/documentation/html

#      - uses: actions/checkout@v2
#      - name: Commit and Push documentation to github
#        run: |
#          git config --global user.name 'game4u4me'
#          git config --global user.email 'game4u4me2@gmail.com'
#          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
#          git add .
#          git commit -am "Automated report"
#          git push

  unit-test:
    needs: [ lint ]
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run tests
        run: ./gradlew test

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

  build:
    needs: [ unit-test ]
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
          token: ${{ secrets.MY_TOKEN || github.token }}

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload app
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk/debug/**.apk